language: rust
cache: cargo
rust: nightly
script:
- cargo test --verbose
- cargo build
- if rustup component add clippy ; then cargo clippy --all-targets -- -D warnings
  ; else echo "no clippy"; fi
deploy:
  provider: script
  script: make docker-login docker-push
  on:
    branch: master
env:
  global:
    secure: sEhpaFdQlnvLP1YPdvS4unv2aOQebkQRvYm+wz09fYjSaQs1TLY8cNWms0Vzn6HthxNhsdmqLQgo0p+Qo4fO8luDCr/0QUdYjRsin5wrXau/1sVLCeRcPBHPbiMG/lGxZmbyv1CuRb5tYfT1cHzUkdk0/+AlgHOy4k8uhEnobykOyGM2NFCjX/I0kOEPnyUYlcSyvWjm7Sq3TzxNoMtTlEF28Atx/BAB5vIPIRB9Eg7ot/GshAsqHRHhy7Pw0S8spQcjQchuhJfLPWm6P296T9n81P7HHvZx3JPpI7T2x1je2apm+f0c+1+TG30J7DXuq8Yp+hhbjtHWCcgw8qGds8ivH1w0Xee/Q3jyvFdR+CjNpfLjMIfA9dtWK5nalMEKjP95JOyscOjnHAEq2Lxi5NOM3EL72lquD5J28ycQjQtuyc+jATWyYqJRBrzMhOii9msfrd6wOoreA+nxM+0DG6tT/ABJSt/BvxM/wameN0TaRTqVf6Fq/Un+HChGanxuM5bCbFzAQStCu1FNPxlbwCV6573JmOhRQVh/TbLeoJU7rHfniRWG12rg5yXErth8ati1poUb3njANmNLTwL9ntoYX0Jd3QC5lwdfFNMsi5x5+4Y/Sh57pJ8Cx2KGb4K/3lNQkRFsFaCLfIMhm3DFeeK9ofsYEdaRdQBi09IJ14E=
