version: 2
jobs:
  test-image:
    docker:
    - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: "Run tests"
          command: cargo test --verbose
      - run:
          name: "Build all packages"
          command: cargo build --verbose
      - run:
          name: "Build all packages"
          command: cargo build --release

workflows:
  version: 2
  run:
    jobs:
      - test-image
