version: 2
jobs:
  test:
    docker:
    - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: "Build all packages"
          command: cargo build --verbose
      - run:
          name: "Run tests"
          command: cargo test --verbose
  build:
    docker:
    - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: "Build release package"
          command: cargo build --release
      - setup_remote_docker
      - run: make docker-login
      - run: make docker-push

workflows:
  version: 2
  run:
    jobs:
      - test
      - build:
          filters:
            branches:
              only: circle
    
