[package]
name = "minify"
version = "0.1.0"
authors = ["Ellie Frost <web@stillinbeta.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.1"
minifier = "0.0.29"
proc-macro2 = "0.4"
syn = { version = "0.15.29", features = ["parsing"] }