[package]
name = "sibcom2"
version = "0.1.0"
authors = ["Ellie Frost <web@stillinbeta.com>"]
edition = "2018"

build = "build.rs"

[dependencies]
generator = { path = "../generator" }
bmon = { path = "../bmon" }
fastly = "0.7"
