[package]
name = "sibcom2"
version = "0.1.0"
authors = ["Ellie Frost <web@stillinbeta.com>"]
edition = "2021"

build = "build.rs"

[dependencies]
generator = { path = "../generator" }
bmon = { path = "../bmon" }
rocket = "0.5.0-rc.2"
