[package]
name = "bmon"
description = "Beta's Magical Object Notation"
version = "0.1.0"
authors = ["Ellie Frost <web@stillinbeta.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rocket = "0.4"

[dev-dependencies]
serde_yaml = "0.8"
