[package]
name = "bmon"
description = "Beta's Magical Object Notation"
version = "0.1.0"
authors = ["Ellie Frost <web@stillinbeta.com>"]
edition = "2018"

[dependencies]
quote = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
rocket = "0.4"
htmlescape = "0.3"
proc-macro2 = "0.4"
serde_yaml = "0.8"


[dev-dependencies]
serde_yaml = "0.8"
